# Generated by Django 5.2.7 on 2026-05-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_CLIENTE', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=40, null=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=30, null=True)),
                ('contraseña', models.CharField(db_column='CONTRASEÑA', max_length=256)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='NOMBRE_PRODUCTO', max_length=30, null=True)),
                ('precio_producto', models.DecimalField(blank=True, db_column='PRECIO_PRODUCTO', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(db_column='PEDIDO_ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', default='Procesando', max_length=30, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='ID_CLIENTE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.cliente')),
            ],
            options={
                'db_table': 'PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.IntegerField(db_column='ID_DETALLE_PEDIDO', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('pedido_id', models.ForeignKey(db_column='ID_PEDIDO', default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pedido')),
                ('id_producto', models.ForeignKey(db_column='ID_PRODUCTO', default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.producto')),
            ],
            options={
                'db_table': 'DETALLE_PEDIDO',
                'managed': True,
            },
        ),
    ]
