# Generated by Django 5.2.8 on 2026-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Componentes', 'Componentes'), ('Periféricos', 'Periféricos'), ('Accesorios', 'Accesorios'), ('GPUs', 'GPUs'), ('Monitores', 'Monitores'), ('Consolas', 'Consolas'), ('Auriculares', 'Auriculares'), ('Bocinas', 'Bocinas'), ('Headsets', 'Headsets'), ('Sistemas', 'Sistemas'), ('Smartwatches', 'Smartwatches'), ('Teléfonos', 'Teléfonos'), ('Tablets', 'Tablets'), ('Accesorios Inteligentes', 'Accesorios Inteligentes')], max_length=100),
        ),
    ]
