# Generated by Django 5.2.7 on 2026-05-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
